[package]
authors = ["Wu Young <doomsplayer@gmail.com>"]
name = "sidekiq-rs"
version = "0.1.0"
license = "MIT"
description = "Sidekiq compatible server in Rust"
homepage = "https://github.com/doomsplayer/sidekiq-rs"
repository = "https://github.com/doomsplayer/sidekiq-rs"


[lib]
name = "sidekiqrs"

[dependencies]
chan = "0.1.18"
chrono = "0.2.25"
docopt = "0.6.82"
docopt_macros = "0.6.85"
env_logger = "0.3.4"
error-chain = "*"
json = "0.10.2"
libc = "*"
log = "0.3.6"
r2d2 = "0.7.0"
r2d2_redis = "0.4.0"
rand = "0.3.14"
random_choice = "0.3.0"
redis = "0.6.0"
rustc-serialize = "0.3.19"
serde = "0.8"
serde_json = "0.8"
serde_macros = "0.8"
threadpool = "1.0.0"